version: '3'
services:
  php-workspace:
    build: ./php
    volumes: # 这里指定数据卷，可以指定多个，中划线代表值为数组的一个成员
      - ./code:/var/www/html
    depends_on: # 指定先启动数据库服务,再启动redis
      - mysql
      - redis
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www/html #将来访问静态文件也是需要www目录，所以nginx也拷贝一份
      - ./conf:/etc/nginx/conf.d
  mysql:
    build: ./mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:5.0.6-alpine
    ports:
      - "6379:6379"